# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Sat Jan  8 22:43:11 2011
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(693, 786)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.pageList = DropListWidget(self.centralwidget)
        self.pageList.setStyleSheet(_fromUtf8("QListView\n"
"{\n"
"background-image: url(\"./icons/go-down-big.png\");\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"background-color: white;\n"
"}\n"
"\n"
"QListView:hover\n"
"{\n"
"background-image: url(\"./icons/go-down-big-hover.png\");\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"background-color: white;\n"
"}"))
        self.pageList.setObjectName(_fromUtf8("pageList"))
        self.verticalLayout_2.addWidget(self.pageList)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.addPageButton = QtGui.QPushButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/list-add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addPageButton.setIcon(icon)
        self.addPageButton.setObjectName(_fromUtf8("addPageButton"))
        self.horizontalLayout_2.addWidget(self.addPageButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.removePageButton = QtGui.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/list-remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removePageButton.setIcon(icon1)
        self.removePageButton.setAutoRepeat(False)
        self.removePageButton.setFlat(False)
        self.removePageButton.setObjectName(_fromUtf8("removePageButton"))
        self.horizontalLayout_2.addWidget(self.removePageButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_3.addWidget(self.line)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.formLayout_2 = QtGui.QFormLayout(self.tab1)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.enableOCR = QtGui.QCheckBox(self.tab1)
        self.enableOCR.setObjectName(_fromUtf8("enableOCR"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.SpanningRole, self.enableOCR)
        self.ocrEngine = QtGui.QComboBox(self.tab1)
        self.ocrEngine.setEnabled(False)
        self.ocrEngine.setObjectName(_fromUtf8("ocrEngine"))
        self.ocrEngine.addItem(_fromUtf8(""))
        self.ocrEngine.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.ocrEngine)
        self.ocrEngineLabel = QtGui.QLabel(self.tab1)
        self.ocrEngineLabel.setObjectName(_fromUtf8("ocrEngineLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.ocrEngineLabel)
        self.ocrOptions = QtGui.QLineEdit(self.tab1)
        self.ocrOptions.setEnabled(False)
        self.ocrOptions.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ocrOptions.setObjectName(_fromUtf8("ocrOptions"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.ocrOptions)
        self.ocrOptionsLabel = QtGui.QLabel(self.tab1)
        self.ocrOptionsLabel.setEnabled(True)
        self.ocrOptionsLabel.setObjectName(_fromUtf8("ocrOptionsLabel"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.ocrOptionsLabel)
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.formLayout_3 = QtGui.QFormLayout(self.tab2)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.bitonalEncoder = QtGui.QComboBox(self.tab2)
        self.bitonalEncoder.setObjectName(_fromUtf8("bitonalEncoder"))
        self.bitonalEncoder.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.bitonalEncoder)
        self.bitonalEncoderLabel = QtGui.QLabel(self.tab2)
        self.bitonalEncoderLabel.setObjectName(_fromUtf8("bitonalEncoderLabel"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.bitonalEncoderLabel)
        self.colorEncoder = QtGui.QComboBox(self.tab2)
        self.colorEncoder.setObjectName(_fromUtf8("colorEncoder"))
        self.colorEncoder.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.colorEncoder)
        self.colorEncoderLabel = QtGui.QLabel(self.tab2)
        self.colorEncoderLabel.setObjectName(_fromUtf8("colorEncoderLabel"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.colorEncoderLabel)
        self.c44Options = QtGui.QLineEdit(self.tab2)
        self.c44Options.setObjectName(_fromUtf8("c44Options"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.c44Options)
        self.c44OptionsLabel = QtGui.QLabel(self.tab2)
        self.c44OptionsLabel.setObjectName(_fromUtf8("c44OptionsLabel"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.c44OptionsLabel)
        self.cjb2Options = QtGui.QLineEdit(self.tab2)
        self.cjb2Options.setObjectName(_fromUtf8("cjb2Options"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.cjb2Options)
        self.cjb2OptionsLabel = QtGui.QLabel(self.tab2)
        self.cjb2OptionsLabel.setObjectName(_fromUtf8("cjb2OptionsLabel"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.cjb2OptionsLabel)
        self.cpaldjvuOptions = QtGui.QLineEdit(self.tab2)
        self.cpaldjvuOptions.setObjectName(_fromUtf8("cpaldjvuOptions"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.cpaldjvuOptions)
        self.cpaldjvuOptionsLabel = QtGui.QLabel(self.tab2)
        self.cpaldjvuOptionsLabel.setObjectName(_fromUtf8("cpaldjvuOptionsLabel"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.cpaldjvuOptionsLabel)
        self.csepdjvuOptions = QtGui.QLineEdit(self.tab2)
        self.csepdjvuOptions.setObjectName(_fromUtf8("csepdjvuOptions"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.csepdjvuOptions)
        self.csepdjvuOptionsLabel = QtGui.QLabel(self.tab2)
        self.csepdjvuOptionsLabel.setObjectName(_fromUtf8("csepdjvuOptionsLabel"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.csepdjvuOptionsLabel)
        self.minidjvuOptions = QtGui.QLineEdit(self.tab2)
        self.minidjvuOptions.setObjectName(_fromUtf8("minidjvuOptions"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.FieldRole, self.minidjvuOptions)
        self.minidjvuOptionsLabel = QtGui.QLabel(self.tab2)
        self.minidjvuOptionsLabel.setObjectName(_fromUtf8("minidjvuOptionsLabel"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.minidjvuOptionsLabel)
        self.tabWidget.addTab(self.tab2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.startButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/media-playback-start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startButton.setIcon(icon2)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.horizontalLayout_5.addWidget(self.startButton)
        self.stopButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/media-playback-stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon3)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.horizontalLayout_5.addWidget(self.stopButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setProperty(_fromUtf8("value"), 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setEnabled(True)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionSave_as_2 = QtGui.QAction(MainWindow)
        self.actionSave_as_2.setObjectName(_fromUtf8("actionSave_as_2"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Bindery", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Drop the book\'s pages below", None, QtGui.QApplication.UnicodeUTF8))
        self.addPageButton.setText(QtGui.QApplication.translate("MainWindow", "Add page", None, QtGui.QApplication.UnicodeUTF8))
        self.removePageButton.setText(QtGui.QApplication.translate("MainWindow", "Remove page", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Configure the binding options below", None, QtGui.QApplication.UnicodeUTF8))
        self.enableOCR.setText(QtGui.QApplication.translate("MainWindow", "Enable OCR", None, QtGui.QApplication.UnicodeUTF8))
        self.ocrEngine.setItemText(0, QtGui.QApplication.translate("MainWindow", "Tesseract", None, QtGui.QApplication.UnicodeUTF8))
        self.ocrEngine.setItemText(1, QtGui.QApplication.translate("MainWindow", "Cuniform", None, QtGui.QApplication.UnicodeUTF8))
        self.ocrEngineLabel.setText(QtGui.QApplication.translate("MainWindow", "OCR Engine", None, QtGui.QApplication.UnicodeUTF8))
        self.ocrOptionsLabel.setText(QtGui.QApplication.translate("MainWindow", "Engine Options", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), QtGui.QApplication.translate("MainWindow", "OCR", None, QtGui.QApplication.UnicodeUTF8))
        self.bitonalEncoder.setItemText(0, QtGui.QApplication.translate("MainWindow", "cjb2", None, QtGui.QApplication.UnicodeUTF8))
        self.bitonalEncoderLabel.setText(QtGui.QApplication.translate("MainWindow", "Bitonal Encoder", None, QtGui.QApplication.UnicodeUTF8))
        self.colorEncoder.setItemText(0, QtGui.QApplication.translate("MainWindow", "csepdjvu", None, QtGui.QApplication.UnicodeUTF8))
        self.colorEncoderLabel.setText(QtGui.QApplication.translate("MainWindow", "Color Encoder", None, QtGui.QApplication.UnicodeUTF8))
        self.c44OptionsLabel.setText(QtGui.QApplication.translate("MainWindow", "c44 Options", None, QtGui.QApplication.UnicodeUTF8))
        self.cjb2Options.setText(QtGui.QApplication.translate("MainWindow", "-lossy", None, QtGui.QApplication.UnicodeUTF8))
        self.cjb2OptionsLabel.setText(QtGui.QApplication.translate("MainWindow", "cjb2 Options", None, QtGui.QApplication.UnicodeUTF8))
        self.cpaldjvuOptionsLabel.setText(QtGui.QApplication.translate("MainWindow", "cpaldjvu Options", None, QtGui.QApplication.UnicodeUTF8))
        self.csepdjvuOptionsLabel.setText(QtGui.QApplication.translate("MainWindow", "csepdjvu Options", None, QtGui.QApplication.UnicodeUTF8))
        self.minidjvuOptions.setText(QtGui.QApplication.translate("MainWindow", "--match -pages-per-dict 100", None, QtGui.QApplication.UnicodeUTF8))
        self.minidjvuOptionsLabel.setText(QtGui.QApplication.translate("MainWindow", "minidjvu Options", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), QtGui.QApplication.translate("MainWindow", "Encoders", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.progressBar.setFormat(QtGui.QApplication.translate("MainWindow", "%p%", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setText(QtGui.QApplication.translate("MainWindow", "Save as", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as_2.setText(QtGui.QApplication.translate("MainWindow", "Save as", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

from DropListWidget import DropListWidget
import resources_rc
