# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Thu Jan 13 16:42:13 2011
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(693, 786)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.pageList = DropListWidget(self.centralwidget)
        self.pageList.setStyleSheet(_fromUtf8("QListView\n"
"{\n"
"background-image: url(\"./icons/go-down-big.png\");\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"background-color: white;\n"
"}\n"
"\n"
"QListView:hover\n"
"{\n"
"background-image: url(\"./icons/go-down-big-hover.png\");\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"background-color: white;\n"
"}"))
        self.pageList.setObjectName(_fromUtf8("pageList"))
        self.verticalLayout_2.addWidget(self.pageList)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.addPageButton = QtGui.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/list-add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addPageButton.setIcon(icon1)
        self.addPageButton.setObjectName(_fromUtf8("addPageButton"))
        self.horizontalLayout_2.addWidget(self.addPageButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.removePageButton = QtGui.QPushButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/list-remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removePageButton.setIcon(icon2)
        self.removePageButton.setAutoRepeat(False)
        self.removePageButton.setFlat(False)
        self.removePageButton.setObjectName(_fromUtf8("removePageButton"))
        self.horizontalLayout_2.addWidget(self.removePageButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_3.addWidget(self.line)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.formLayout_4 = QtGui.QFormLayout(self.tab_2)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.pageNumber = QtGui.QLineEdit(self.tab_2)
        self.pageNumber.setObjectName(_fromUtf8("pageNumber"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.pageNumber)
        self.pageNumberLabel = QtGui.QLabel(self.tab_2)
        self.pageNumberLabel.setObjectName(_fromUtf8("pageNumberLabel"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.pageNumberLabel)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.formLayout = QtGui.QFormLayout(self.tab)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.outputFormat = QtGui.QComboBox(self.tab)
        self.outputFormat.setObjectName(_fromUtf8("outputFormat"))
        self.outputFormat.addItem(_fromUtf8(""))
        self.outputFormat.addItem(_fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.outputFormat)
        self.outputFormatLabel = QtGui.QLabel(self.tab)
        self.outputFormatLabel.setObjectName(_fromUtf8("outputFormatLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.outputFormatLabel)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.formLayout_2 = QtGui.QFormLayout(self.tab1)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.enableOCR = QtGui.QCheckBox(self.tab1)
        self.enableOCR.setObjectName(_fromUtf8("enableOCR"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.SpanningRole, self.enableOCR)
        self.ocrEngine = QtGui.QComboBox(self.tab1)
        self.ocrEngine.setEnabled(False)
        self.ocrEngine.setObjectName(_fromUtf8("ocrEngine"))
        self.ocrEngine.addItem(_fromUtf8(""))
        self.ocrEngine.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.ocrEngine)
        self.ocrEngineLabel = QtGui.QLabel(self.tab1)
        self.ocrEngineLabel.setObjectName(_fromUtf8("ocrEngineLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.ocrEngineLabel)
        self.ocrOptions = QtGui.QLineEdit(self.tab1)
        self.ocrOptions.setEnabled(False)
        self.ocrOptions.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ocrOptions.setObjectName(_fromUtf8("ocrOptions"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.ocrOptions)
        self.ocrOptionsLabel = QtGui.QLabel(self.tab1)
        self.ocrOptionsLabel.setEnabled(True)
        self.ocrOptionsLabel.setObjectName(_fromUtf8("ocrOptionsLabel"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.ocrOptionsLabel)
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.formLayout_3 = QtGui.QFormLayout(self.tab2)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.bitonalEncoder = QtGui.QComboBox(self.tab2)
        self.bitonalEncoder.setObjectName(_fromUtf8("bitonalEncoder"))
        self.bitonalEncoder.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.bitonalEncoder)
        self.bitonalEncoderLabel = QtGui.QLabel(self.tab2)
        self.bitonalEncoderLabel.setObjectName(_fromUtf8("bitonalEncoderLabel"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.bitonalEncoderLabel)
        self.colorEncoder = QtGui.QComboBox(self.tab2)
        self.colorEncoder.setObjectName(_fromUtf8("colorEncoder"))
        self.colorEncoder.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.colorEncoder)
        self.colorEncoderLabel = QtGui.QLabel(self.tab2)
        self.colorEncoderLabel.setObjectName(_fromUtf8("colorEncoderLabel"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.colorEncoderLabel)
        self.c44Options = QtGui.QLineEdit(self.tab2)
        self.c44Options.setObjectName(_fromUtf8("c44Options"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.c44Options)
        self.c44OptionsLabel = QtGui.QLabel(self.tab2)
        self.c44OptionsLabel.setObjectName(_fromUtf8("c44OptionsLabel"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.c44OptionsLabel)
        self.cjb2Options = QtGui.QLineEdit(self.tab2)
        self.cjb2Options.setObjectName(_fromUtf8("cjb2Options"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.cjb2Options)
        self.cjb2OptionsLabel = QtGui.QLabel(self.tab2)
        self.cjb2OptionsLabel.setObjectName(_fromUtf8("cjb2OptionsLabel"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.cjb2OptionsLabel)
        self.cpaldjvuOptions = QtGui.QLineEdit(self.tab2)
        self.cpaldjvuOptions.setObjectName(_fromUtf8("cpaldjvuOptions"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.cpaldjvuOptions)
        self.cpaldjvuOptionsLabel = QtGui.QLabel(self.tab2)
        self.cpaldjvuOptionsLabel.setObjectName(_fromUtf8("cpaldjvuOptionsLabel"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.cpaldjvuOptionsLabel)
        self.csepdjvuOptions = QtGui.QLineEdit(self.tab2)
        self.csepdjvuOptions.setObjectName(_fromUtf8("csepdjvuOptions"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.csepdjvuOptions)
        self.csepdjvuOptionsLabel = QtGui.QLabel(self.tab2)
        self.csepdjvuOptionsLabel.setObjectName(_fromUtf8("csepdjvuOptionsLabel"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.csepdjvuOptionsLabel)
        self.minidjvuOptions = QtGui.QLineEdit(self.tab2)
        self.minidjvuOptions.setObjectName(_fromUtf8("minidjvuOptions"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.FieldRole, self.minidjvuOptions)
        self.minidjvuOptionsLabel = QtGui.QLabel(self.tab2)
        self.minidjvuOptionsLabel.setObjectName(_fromUtf8("minidjvuOptionsLabel"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.minidjvuOptionsLabel)
        self.tabWidget.addTab(self.tab2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.startButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/media-playback-start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startButton.setIcon(icon3)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.horizontalLayout_5.addWidget(self.startButton)
        self.stopButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("./icons/media-playback-stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon4)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.horizontalLayout_5.addWidget(self.stopButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setEnabled(True)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 693, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menuBar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuAbout = QtGui.QMenu(self.menuBar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionSave_as_2 = QtGui.QAction(MainWindow)
        self.actionSave_as_2.setObjectName(_fromUtf8("actionSave_as_2"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.newMenuButton = QtGui.QAction(MainWindow)
        self.newMenuButton.setObjectName(_fromUtf8("newMenuButton"))
        self.openMenuItem = QtGui.QAction(MainWindow)
        self.openMenuItem.setObjectName(_fromUtf8("openMenuItem"))
        self.saveMenuItem = QtGui.QAction(MainWindow)
        self.saveMenuItem.setObjectName(_fromUtf8("saveMenuItem"))
        self.saveAsMenuItem = QtGui.QAction(MainWindow)
        self.saveAsMenuItem.setObjectName(_fromUtf8("saveAsMenuItem"))
        self.quitMenuItem = QtGui.QAction(MainWindow)
        self.quitMenuItem.setObjectName(_fromUtf8("quitMenuItem"))
        self.helpMenuItem = QtGui.QAction(MainWindow)
        self.helpMenuItem.setObjectName(_fromUtf8("helpMenuItem"))
        self.aboutMenuItem = QtGui.QAction(MainWindow)
        self.aboutMenuItem.setObjectName(_fromUtf8("aboutMenuItem"))
        self.filePreviewsMenuItem = QtGui.QAction(MainWindow)
        self.filePreviewsMenuItem.setCheckable(True)
        self.filePreviewsMenuItem.setChecked(True)
        self.filePreviewsMenuItem.setObjectName(_fromUtf8("filePreviewsMenuItem"))
        self.advancedOptionsMenuItem = QtGui.QAction(MainWindow)
        self.advancedOptionsMenuItem.setCheckable(True)
        self.advancedOptionsMenuItem.setChecked(True)
        self.advancedOptionsMenuItem.setObjectName(_fromUtf8("advancedOptionsMenuItem"))
        self.menuFile.addAction(self.newMenuButton)
        self.menuFile.addAction(self.openMenuItem)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.saveMenuItem)
        self.menuFile.addAction(self.saveAsMenuItem)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.quitMenuItem)
        self.menuEdit.addAction(self.filePreviewsMenuItem)
        self.menuEdit.addAction(self.advancedOptionsMenuItem)
        self.menuAbout.addAction(self.helpMenuItem)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.aboutMenuItem)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Bindery", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Add and arrange the book\'s pages below", None, QtGui.QApplication.UnicodeUTF8))
        self.addPageButton.setText(QtGui.QApplication.translate("MainWindow", "Add page", None, QtGui.QApplication.UnicodeUTF8))
        self.removePageButton.setText(QtGui.QApplication.translate("MainWindow", "Remove page", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Configure the binding options below", None, QtGui.QApplication.UnicodeUTF8))
        self.pageNumberLabel.setText(QtGui.QApplication.translate("MainWindow", "Page Number", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Page", None, QtGui.QApplication.UnicodeUTF8))
        self.outputFormat.setItemText(0, QtGui.QApplication.translate("MainWindow", "DjVu", None, QtGui.QApplication.UnicodeUTF8))
        self.outputFormat.setItemText(1, QtGui.QApplication.translate("MainWindow", "PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.outputFormatLabel.setText(QtGui.QApplication.translate("MainWindow", "Output Format", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Book", None, QtGui.QApplication.UnicodeUTF8))
        self.enableOCR.setText(QtGui.QApplication.translate("MainWindow", "Enable OCR", None, QtGui.QApplication.UnicodeUTF8))
        self.ocrEngine.setItemText(0, QtGui.QApplication.translate("MainWindow", "Tesseract", None, QtGui.QApplication.UnicodeUTF8))
        self.ocrEngine.setItemText(1, QtGui.QApplication.translate("MainWindow", "Cuniform", None, QtGui.QApplication.UnicodeUTF8))
        self.ocrEngineLabel.setText(QtGui.QApplication.translate("MainWindow", "OCR Engine", None, QtGui.QApplication.UnicodeUTF8))
        self.ocrOptionsLabel.setText(QtGui.QApplication.translate("MainWindow", "Engine Options", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), QtGui.QApplication.translate("MainWindow", "OCR", None, QtGui.QApplication.UnicodeUTF8))
        self.bitonalEncoder.setItemText(0, QtGui.QApplication.translate("MainWindow", "cjb2", None, QtGui.QApplication.UnicodeUTF8))
        self.bitonalEncoderLabel.setText(QtGui.QApplication.translate("MainWindow", "Bitonal Encoder", None, QtGui.QApplication.UnicodeUTF8))
        self.colorEncoder.setItemText(0, QtGui.QApplication.translate("MainWindow", "csepdjvu", None, QtGui.QApplication.UnicodeUTF8))
        self.colorEncoderLabel.setText(QtGui.QApplication.translate("MainWindow", "Color Encoder", None, QtGui.QApplication.UnicodeUTF8))
        self.c44OptionsLabel.setText(QtGui.QApplication.translate("MainWindow", "c44 Options", None, QtGui.QApplication.UnicodeUTF8))
        self.cjb2Options.setText(QtGui.QApplication.translate("MainWindow", "-lossy", None, QtGui.QApplication.UnicodeUTF8))
        self.cjb2OptionsLabel.setText(QtGui.QApplication.translate("MainWindow", "cjb2 Options", None, QtGui.QApplication.UnicodeUTF8))
        self.cpaldjvuOptionsLabel.setText(QtGui.QApplication.translate("MainWindow", "cpaldjvu Options", None, QtGui.QApplication.UnicodeUTF8))
        self.csepdjvuOptionsLabel.setText(QtGui.QApplication.translate("MainWindow", "csepdjvu Options", None, QtGui.QApplication.UnicodeUTF8))
        self.minidjvuOptions.setText(QtGui.QApplication.translate("MainWindow", "--match -pages-per-dict 100", None, QtGui.QApplication.UnicodeUTF8))
        self.minidjvuOptionsLabel.setText(QtGui.QApplication.translate("MainWindow", "minidjvu Options", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), QtGui.QApplication.translate("MainWindow", "DjVu Encoders", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setText(QtGui.QApplication.translate("MainWindow", "Save as", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as_2.setText(QtGui.QApplication.translate("MainWindow", "Save as", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.newMenuButton.setText(QtGui.QApplication.translate("MainWindow", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.newMenuButton.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.openMenuItem.setText(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.openMenuItem.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.saveMenuItem.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.saveMenuItem.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAsMenuItem.setText(QtGui.QApplication.translate("MainWindow", "Save &As...", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAsMenuItem.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Alt+S", None, QtGui.QApplication.UnicodeUTF8))
        self.quitMenuItem.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.quitMenuItem.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.helpMenuItem.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.helpMenuItem.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutMenuItem.setText(QtGui.QApplication.translate("MainWindow", "About Bindery", None, QtGui.QApplication.UnicodeUTF8))
        self.filePreviewsMenuItem.setText(QtGui.QApplication.translate("MainWindow", "File Previews", None, QtGui.QApplication.UnicodeUTF8))
        self.advancedOptionsMenuItem.setText(QtGui.QApplication.translate("MainWindow", "Advanced Options", None, QtGui.QApplication.UnicodeUTF8))

from DropListWidget import DropListWidget
import resources_rc
