# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Mon Feb  7 12:14:49 2011
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
  _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
  _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
  def setupUi(self, MainWindow):
    MainWindow.setObjectName(_fromUtf8("MainWindow"))
    MainWindow.setEnabled(True)
    MainWindow.resize(559, 832)
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    MainWindow.setWindowIcon(icon)
    MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
    self.centralwidget = QtGui.QWidget(MainWindow)
    self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
    self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
    self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
    self.mainTabWidget = QtGui.QTabWidget(self.centralwidget)
    self.mainTabWidget.setObjectName(_fromUtf8("mainTabWidget"))
    self.tab = QtGui.QWidget()
    self.tab.setObjectName(_fromUtf8("tab"))
    self.gridLayout_2 = QtGui.QGridLayout(self.tab)
    self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
    self.label = QtGui.QLabel(self.tab)
    self.label.setAlignment(QtCore.Qt.AlignCenter)
    self.label.setObjectName(_fromUtf8("label"))
    self.gridLayout_2.addWidget(self.label, 0, 0, 1, 3)
    self.pageList = BookListWidget(self.tab)
    self.pageList.setStyleSheet(_fromUtf8("QListView\n"
"{\n"
"background-image: url(\":/icons/go-down-big.png\");\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"background-color: white;\n"
"}\n"
"\n"
"QListView:hover\n"
"{\n"
"background-image: url(\":/icons/go-down-big-hover.png\");\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"background-color: white;\n"
"}"))
    self.pageList.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
    self.pageList.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
    self.pageList.setUniformItemSizes(True)
    self.pageList.setObjectName(_fromUtf8("pageList"))
    self.gridLayout_2.addWidget(self.pageList, 1, 0, 1, 3)
    self.verticalLayout = QtGui.QVBoxLayout()
    self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
    self.pageGrayscale = QtGui.QCheckBox(self.tab)
    self.pageGrayscale.setEnabled(False)
    self.pageGrayscale.setObjectName(_fromUtf8("pageGrayscale"))
    self.verticalLayout.addWidget(self.pageGrayscale)
    spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
    self.verticalLayout.addItem(spacerItem)
    self.gridLayout_2.addLayout(self.verticalLayout, 1, 3, 1, 1)
    self.addPageButton = QtGui.QPushButton(self.tab)
    icon1 = QtGui.QIcon()
    icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/list-add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.addPageButton.setIcon(icon1)
    self.addPageButton.setObjectName(_fromUtf8("addPageButton"))
    self.gridLayout_2.addWidget(self.addPageButton, 2, 0, 1, 1)
    spacerItem1 = QtGui.QSpacerItem(166, 24, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
    self.gridLayout_2.addItem(spacerItem1, 2, 1, 1, 1)
    self.label_2 = QtGui.QLabel(self.tab)
    self.label_2.setObjectName(_fromUtf8("label_2"))
    self.gridLayout_2.addWidget(self.label_2, 0, 3, 1, 1)
    self.removePageButton = QtGui.QPushButton(self.tab)
    icon2 = QtGui.QIcon()
    icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/list-remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.removePageButton.setIcon(icon2)
    self.removePageButton.setAutoRepeat(False)
    self.removePageButton.setFlat(False)
    self.removePageButton.setObjectName(_fromUtf8("removePageButton"))
    self.gridLayout_2.addWidget(self.removePageButton, 2, 2, 1, 1)
    self.mainTabWidget.addTab(self.tab, _fromUtf8(""))
    self.tab_2 = QtGui.QWidget()
    self.tab_2.setObjectName(_fromUtf8("tab_2"))
    self.gridLayout = QtGui.QGridLayout(self.tab_2)
    self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
    self.splitter = QtGui.QSplitter(self.tab_2)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
    self.splitter.setSizePolicy(sizePolicy)
    self.splitter.setOrientation(QtCore.Qt.Horizontal)
    self.splitter.setHandleWidth(8)
    self.splitter.setChildrenCollapsible(False)
    self.splitter.setObjectName(_fromUtf8("splitter"))
    self.layoutWidget = QtGui.QWidget(self.splitter)
    self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
    self.verticalLayout1 = QtGui.QVBoxLayout(self.layoutWidget)
    self.verticalLayout1.setObjectName(_fromUtf8("verticalLayout1"))
    self.tabWidget = QtGui.QTabWidget(self.layoutWidget)
    self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
    self.tabWidget.setMovable(True)
    self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
    self.tab2 = QtGui.QWidget()
    self.tab2.setObjectName(_fromUtf8("tab2"))
    self.formLayout_10 = QtGui.QFormLayout(self.tab2)
    self.formLayout_10.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
    self.formLayout_10.setObjectName(_fromUtf8("formLayout_10"))
    self.outputFormat = QtGui.QComboBox(self.tab2)
    self.outputFormat.setObjectName(_fromUtf8("outputFormat"))
    self.outputFormat.addItem(_fromUtf8(""))
    self.outputFormat.addItem(_fromUtf8(""))
    self.formLayout_10.setWidget(0, QtGui.QFormLayout.FieldRole, self.outputFormat)
    self.outputFormatLabel = QtGui.QLabel(self.tab2)
    self.outputFormatLabel.setObjectName(_fromUtf8("outputFormatLabel"))
    self.formLayout_10.setWidget(0, QtGui.QFormLayout.LabelRole, self.outputFormatLabel)
    self.tabWidget.addTab(self.tab2, _fromUtf8(""))
    self.tab3 = QtGui.QWidget()
    self.tab3.setObjectName(_fromUtf8("tab3"))
    self.formLayout_11 = QtGui.QFormLayout(self.tab3)
    self.formLayout_11.setObjectName(_fromUtf8("formLayout_11"))
    self.enableOCR = QtGui.QCheckBox(self.tab3)
    self.enableOCR.setObjectName(_fromUtf8("enableOCR"))
    self.formLayout_11.setWidget(0, QtGui.QFormLayout.SpanningRole, self.enableOCR)
    self.ocrEngine = QtGui.QComboBox(self.tab3)
    self.ocrEngine.setEnabled(False)
    self.ocrEngine.setObjectName(_fromUtf8("ocrEngine"))
    self.ocrEngine.addItem(_fromUtf8(""))
    self.ocrEngine.addItem(_fromUtf8(""))
    self.formLayout_11.setWidget(1, QtGui.QFormLayout.FieldRole, self.ocrEngine)
    self.ocrEngineLabel = QtGui.QLabel(self.tab3)
    self.ocrEngineLabel.setObjectName(_fromUtf8("ocrEngineLabel"))
    self.formLayout_11.setWidget(1, QtGui.QFormLayout.LabelRole, self.ocrEngineLabel)
    self.ocrOptions = QtGui.QLineEdit(self.tab3)
    self.ocrOptions.setEnabled(False)
    self.ocrOptions.setLayoutDirection(QtCore.Qt.LeftToRight)
    self.ocrOptions.setObjectName(_fromUtf8("ocrOptions"))
    self.formLayout_11.setWidget(2, QtGui.QFormLayout.FieldRole, self.ocrOptions)
    self.ocrOptionsLabel = QtGui.QLabel(self.tab3)
    self.ocrOptionsLabel.setEnabled(True)
    self.ocrOptionsLabel.setObjectName(_fromUtf8("ocrOptionsLabel"))
    self.formLayout_11.setWidget(2, QtGui.QFormLayout.LabelRole, self.ocrOptionsLabel)
    self.tabWidget.addTab(self.tab3, _fromUtf8(""))
    self.tab4 = QtGui.QWidget()
    self.tab4.setObjectName(_fromUtf8("tab4"))
    self.formLayout_12 = QtGui.QFormLayout(self.tab4)
    self.formLayout_12.setObjectName(_fromUtf8("formLayout_12"))
    self.bitonalEncoder = QtGui.QComboBox(self.tab4)
    self.bitonalEncoder.setObjectName(_fromUtf8("bitonalEncoder"))
    self.bitonalEncoder.addItem(_fromUtf8(""))
    self.formLayout_12.setWidget(0, QtGui.QFormLayout.FieldRole, self.bitonalEncoder)
    self.bitonalEncoderLabel = QtGui.QLabel(self.tab4)
    self.bitonalEncoderLabel.setObjectName(_fromUtf8("bitonalEncoderLabel"))
    self.formLayout_12.setWidget(0, QtGui.QFormLayout.LabelRole, self.bitonalEncoderLabel)
    self.colorEncoder = QtGui.QComboBox(self.tab4)
    self.colorEncoder.setObjectName(_fromUtf8("colorEncoder"))
    self.colorEncoder.addItem(_fromUtf8(""))
    self.formLayout_12.setWidget(1, QtGui.QFormLayout.FieldRole, self.colorEncoder)
    self.colorEncoderLabel = QtGui.QLabel(self.tab4)
    self.colorEncoderLabel.setObjectName(_fromUtf8("colorEncoderLabel"))
    self.formLayout_12.setWidget(1, QtGui.QFormLayout.LabelRole, self.colorEncoderLabel)
    self.c44Options = QtGui.QLineEdit(self.tab4)
    self.c44Options.setObjectName(_fromUtf8("c44Options"))
    self.formLayout_12.setWidget(2, QtGui.QFormLayout.FieldRole, self.c44Options)
    self.c44OptionsLabel = QtGui.QLabel(self.tab4)
    self.c44OptionsLabel.setObjectName(_fromUtf8("c44OptionsLabel"))
    self.formLayout_12.setWidget(2, QtGui.QFormLayout.LabelRole, self.c44OptionsLabel)
    self.cjb2Options = QtGui.QLineEdit(self.tab4)
    self.cjb2Options.setObjectName(_fromUtf8("cjb2Options"))
    self.formLayout_12.setWidget(3, QtGui.QFormLayout.FieldRole, self.cjb2Options)
    self.cjb2OptionsLabel = QtGui.QLabel(self.tab4)
    self.cjb2OptionsLabel.setObjectName(_fromUtf8("cjb2OptionsLabel"))
    self.formLayout_12.setWidget(3, QtGui.QFormLayout.LabelRole, self.cjb2OptionsLabel)
    self.cpaldjvuOptions = QtGui.QLineEdit(self.tab4)
    self.cpaldjvuOptions.setObjectName(_fromUtf8("cpaldjvuOptions"))
    self.formLayout_12.setWidget(4, QtGui.QFormLayout.FieldRole, self.cpaldjvuOptions)
    self.cpaldjvuOptionsLabel = QtGui.QLabel(self.tab4)
    self.cpaldjvuOptionsLabel.setObjectName(_fromUtf8("cpaldjvuOptionsLabel"))
    self.formLayout_12.setWidget(4, QtGui.QFormLayout.LabelRole, self.cpaldjvuOptionsLabel)
    self.csepdjvuOptions = QtGui.QLineEdit(self.tab4)
    self.csepdjvuOptions.setObjectName(_fromUtf8("csepdjvuOptions"))
    self.formLayout_12.setWidget(5, QtGui.QFormLayout.FieldRole, self.csepdjvuOptions)
    self.csepdjvuOptionsLabel = QtGui.QLabel(self.tab4)
    self.csepdjvuOptionsLabel.setObjectName(_fromUtf8("csepdjvuOptionsLabel"))
    self.formLayout_12.setWidget(5, QtGui.QFormLayout.LabelRole, self.csepdjvuOptionsLabel)
    self.minidjvuOptions = QtGui.QLineEdit(self.tab4)
    self.minidjvuOptions.setFrame(True)
    self.minidjvuOptions.setCursorPosition(0)
    self.minidjvuOptions.setObjectName(_fromUtf8("minidjvuOptions"))
    self.formLayout_12.setWidget(6, QtGui.QFormLayout.FieldRole, self.minidjvuOptions)
    self.minidjvuOptionsLabel = QtGui.QLabel(self.tab4)
    self.minidjvuOptionsLabel.setObjectName(_fromUtf8("minidjvuOptionsLabel"))
    self.formLayout_12.setWidget(6, QtGui.QFormLayout.LabelRole, self.minidjvuOptionsLabel)
    self.tabWidget.addTab(self.tab4, _fromUtf8(""))
    self.verticalLayout1.addWidget(self.tabWidget)
    self.horizontalLayout_3 = QtGui.QHBoxLayout()
    self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
    self.verticalLayout1.addLayout(self.horizontalLayout_3)
    self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
    self.mainTabWidget.addTab(self.tab_2, _fromUtf8(""))
    self.tab_3 = QtGui.QWidget()
    self.tab_3.setObjectName(_fromUtf8("tab_3"))
    self.gridLayout_4 = QtGui.QGridLayout(self.tab_3)
    self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
    self.verticalLayout_2 = QtGui.QVBoxLayout()
    self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
    self.progressLog = QtGui.QTextEdit(self.tab_3)
    font = QtGui.QFont()
    font.setFamily(_fromUtf8("Monospace"))
    self.progressLog.setFont(font)
    self.progressLog.setReadOnly(True)
    self.progressLog.setObjectName(_fromUtf8("progressLog"))
    self.verticalLayout_2.addWidget(self.progressLog)
    self.horizontalLayout = QtGui.QHBoxLayout()
    self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
    self.progressBar = QtGui.QProgressBar(self.tab_3)
    self.progressBar.setInvertedAppearance(False)
    self.progressBar.setObjectName(_fromUtf8("progressBar"))
    self.horizontalLayout.addWidget(self.progressBar)
    self.startButton = QtGui.QPushButton(self.tab_3)
    icon3 = QtGui.QIcon()
    icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/media-playback-start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.startButton.setIcon(icon3)
    self.startButton.setObjectName(_fromUtf8("startButton"))
    self.horizontalLayout.addWidget(self.startButton)
    self.verticalLayout_2.addLayout(self.horizontalLayout)
    self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
    self.mainTabWidget.addTab(self.tab_3, _fromUtf8(""))
    self.gridLayout_3.addWidget(self.mainTabWidget, 0, 0, 1, 1)
    MainWindow.setCentralWidget(self.centralwidget)
    self.statusBar = QtGui.QStatusBar(MainWindow)
    self.statusBar.setEnabled(True)
    self.statusBar.setObjectName(_fromUtf8("statusBar"))
    MainWindow.setStatusBar(self.statusBar)
    self.menuBar = QtGui.QMenuBar(MainWindow)
    self.menuBar.setGeometry(QtCore.QRect(0, 0, 559, 25))
    self.menuBar.setObjectName(_fromUtf8("menuBar"))
    self.menuFile = QtGui.QMenu(self.menuBar)
    self.menuFile.setObjectName(_fromUtf8("menuFile"))
    self.menuEdit = QtGui.QMenu(self.menuBar)
    self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
    self.menuAbout = QtGui.QMenu(self.menuBar)
    self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
    MainWindow.setMenuBar(self.menuBar)
    self.actionNew = QtGui.QAction(MainWindow)
    self.actionNew.setObjectName(_fromUtf8("actionNew"))
    self.actionSave = QtGui.QAction(MainWindow)
    self.actionSave.setObjectName(_fromUtf8("actionSave"))
    self.actionSave_as = QtGui.QAction(MainWindow)
    self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
    self.actionSave_as_2 = QtGui.QAction(MainWindow)
    self.actionSave_as_2.setObjectName(_fromUtf8("actionSave_as_2"))
    self.actionExit = QtGui.QAction(MainWindow)
    self.actionExit.setObjectName(_fromUtf8("actionExit"))
    self.newMenuButton = QtGui.QAction(MainWindow)
    self.newMenuButton.setObjectName(_fromUtf8("newMenuButton"))
    self.openMenuItem = QtGui.QAction(MainWindow)
    self.openMenuItem.setObjectName(_fromUtf8("openMenuItem"))
    self.saveMenuItem = QtGui.QAction(MainWindow)
    self.saveMenuItem.setObjectName(_fromUtf8("saveMenuItem"))
    self.saveAsMenuItem = QtGui.QAction(MainWindow)
    self.saveAsMenuItem.setObjectName(_fromUtf8("saveAsMenuItem"))
    self.quitMenuItem = QtGui.QAction(MainWindow)
    self.quitMenuItem.setObjectName(_fromUtf8("quitMenuItem"))
    self.helpMenuItem = QtGui.QAction(MainWindow)
    self.helpMenuItem.setObjectName(_fromUtf8("helpMenuItem"))
    self.aboutMenuItem = QtGui.QAction(MainWindow)
    self.aboutMenuItem.setObjectName(_fromUtf8("aboutMenuItem"))
    self.filePreviewsMenuItem = QtGui.QAction(MainWindow)
    self.filePreviewsMenuItem.setCheckable(True)
    self.filePreviewsMenuItem.setChecked(True)
    self.filePreviewsMenuItem.setObjectName(_fromUtf8("filePreviewsMenuItem"))
    self.advancedOptionsMenuItem = QtGui.QAction(MainWindow)
    self.advancedOptionsMenuItem.setCheckable(True)
    self.advancedOptionsMenuItem.setChecked(True)
    self.advancedOptionsMenuItem.setObjectName(_fromUtf8("advancedOptionsMenuItem"))
    self.actionAbout_Qt4 = QtGui.QAction(MainWindow)
    self.actionAbout_Qt4.setObjectName(_fromUtf8("actionAbout_Qt4"))
    self.actionAbout_PyQt = QtGui.QAction(MainWindow)
    self.actionAbout_PyQt.setObjectName(_fromUtf8("actionAbout_PyQt"))
    self.menuFile.addAction(self.newMenuButton)
    self.menuFile.addAction(self.openMenuItem)
    self.menuFile.addSeparator()
    self.menuFile.addAction(self.saveMenuItem)
    self.menuFile.addAction(self.saveAsMenuItem)
    self.menuFile.addSeparator()
    self.menuFile.addAction(self.quitMenuItem)
    self.menuEdit.addAction(self.filePreviewsMenuItem)
    self.menuAbout.addAction(self.helpMenuItem)
    self.menuAbout.addSeparator()
    self.menuAbout.addAction(self.aboutMenuItem)
    self.menuAbout.addAction(self.actionAbout_Qt4)
    self.menuAbout.addAction(self.actionAbout_PyQt)
    self.menuBar.addAction(self.menuFile.menuAction())
    self.menuBar.addAction(self.menuEdit.menuAction())
    self.menuBar.addAction(self.menuAbout.menuAction())

    self.retranslateUi(MainWindow)
    self.mainTabWidget.setCurrentIndex(0)
    self.tabWidget.setCurrentIndex(2)
    QtCore.QMetaObject.connectSlotsByName(MainWindow)

  def retranslateUi(self, MainWindow):
    MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Bindery", None, QtGui.QApplication.UnicodeUTF8))
    self.label.setText(QtGui.QApplication.translate("MainWindow", "Add and arrange the book\'s pages below", None, QtGui.QApplication.UnicodeUTF8))
    self.pageGrayscale.setText(QtGui.QApplication.translate("MainWindow", "Grayscale", None, QtGui.QApplication.UnicodeUTF8))
    self.addPageButton.setText(QtGui.QApplication.translate("MainWindow", "Add page", None, QtGui.QApplication.UnicodeUTF8))
    self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Page options", None, QtGui.QApplication.UnicodeUTF8))
    self.removePageButton.setText(QtGui.QApplication.translate("MainWindow", "Remove page", None, QtGui.QApplication.UnicodeUTF8))
    self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Pages", None, QtGui.QApplication.UnicodeUTF8))
    self.outputFormat.setItemText(0, QtGui.QApplication.translate("MainWindow", "DjVu", None, QtGui.QApplication.UnicodeUTF8))
    self.outputFormat.setItemText(1, QtGui.QApplication.translate("MainWindow", "PDF", None, QtGui.QApplication.UnicodeUTF8))
    self.outputFormatLabel.setText(QtGui.QApplication.translate("MainWindow", "Output Format", None, QtGui.QApplication.UnicodeUTF8))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), QtGui.QApplication.translate("MainWindow", "Book", None, QtGui.QApplication.UnicodeUTF8))
    self.enableOCR.setText(QtGui.QApplication.translate("MainWindow", "Enable OCR", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrEngine.setItemText(0, QtGui.QApplication.translate("MainWindow", "Tesseract", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrEngine.setItemText(1, QtGui.QApplication.translate("MainWindow", "Cuniform", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrEngineLabel.setText(QtGui.QApplication.translate("MainWindow", "OCR Engine", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrOptionsLabel.setText(QtGui.QApplication.translate("MainWindow", "Engine Options", None, QtGui.QApplication.UnicodeUTF8))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), QtGui.QApplication.translate("MainWindow", "OCR", None, QtGui.QApplication.UnicodeUTF8))
    self.bitonalEncoder.setItemText(0, QtGui.QApplication.translate("MainWindow", "cjb2", None, QtGui.QApplication.UnicodeUTF8))
    self.bitonalEncoderLabel.setText(QtGui.QApplication.translate("MainWindow", "Bitonal Encoder", None, QtGui.QApplication.UnicodeUTF8))
    self.colorEncoder.setItemText(0, QtGui.QApplication.translate("MainWindow", "csepdjvu", None, QtGui.QApplication.UnicodeUTF8))
    self.colorEncoderLabel.setText(QtGui.QApplication.translate("MainWindow", "Color Encoder", None, QtGui.QApplication.UnicodeUTF8))
    self.c44OptionsLabel.setText(QtGui.QApplication.translate("MainWindow", "c44 Options", None, QtGui.QApplication.UnicodeUTF8))
    self.cjb2Options.setText(QtGui.QApplication.translate("MainWindow", "-lossy", None, QtGui.QApplication.UnicodeUTF8))
    self.cjb2OptionsLabel.setText(QtGui.QApplication.translate("MainWindow", "cjb2 Options", None, QtGui.QApplication.UnicodeUTF8))
    self.cpaldjvuOptionsLabel.setText(QtGui.QApplication.translate("MainWindow", "cpaldjvu Options", None, QtGui.QApplication.UnicodeUTF8))
    self.csepdjvuOptionsLabel.setText(QtGui.QApplication.translate("MainWindow", "csepdjvu Options", None, QtGui.QApplication.UnicodeUTF8))
    self.minidjvuOptions.setText(QtGui.QApplication.translate("MainWindow", "--match -pages-per-dict 100", None, QtGui.QApplication.UnicodeUTF8))
    self.minidjvuOptionsLabel.setText(QtGui.QApplication.translate("MainWindow", "minidjvu Options", None, QtGui.QApplication.UnicodeUTF8))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab4), QtGui.QApplication.translate("MainWindow", "DjVu Encoders", None, QtGui.QApplication.UnicodeUTF8))
    self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
    self.progressLog.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Monospace\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This is where the log text goes. This feature is not yet implemented.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
    self.startButton.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
    self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Binding", None, QtGui.QApplication.UnicodeUTF8))
    self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
    self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
    self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
    self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
    self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
    self.actionSave_as.setText(QtGui.QApplication.translate("MainWindow", "Save as", None, QtGui.QApplication.UnicodeUTF8))
    self.actionSave_as_2.setText(QtGui.QApplication.translate("MainWindow", "Save as", None, QtGui.QApplication.UnicodeUTF8))
    self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
    self.newMenuButton.setText(QtGui.QApplication.translate("MainWindow", "&New", None, QtGui.QApplication.UnicodeUTF8))
    self.newMenuButton.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
    self.openMenuItem.setText(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
    self.openMenuItem.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
    self.saveMenuItem.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
    self.saveMenuItem.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
    self.saveAsMenuItem.setText(QtGui.QApplication.translate("MainWindow", "Save &As...", None, QtGui.QApplication.UnicodeUTF8))
    self.saveAsMenuItem.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Alt+S", None, QtGui.QApplication.UnicodeUTF8))
    self.quitMenuItem.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
    self.quitMenuItem.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
    self.helpMenuItem.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
    self.helpMenuItem.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
    self.aboutMenuItem.setText(QtGui.QApplication.translate("MainWindow", "About Bindery", None, QtGui.QApplication.UnicodeUTF8))
    self.filePreviewsMenuItem.setText(QtGui.QApplication.translate("MainWindow", "File Previews", None, QtGui.QApplication.UnicodeUTF8))
    self.advancedOptionsMenuItem.setText(QtGui.QApplication.translate("MainWindow", "Advanced Options", None, QtGui.QApplication.UnicodeUTF8))
    self.actionAbout_Qt4.setText(QtGui.QApplication.translate("MainWindow", "About Qt", None, QtGui.QApplication.UnicodeUTF8))
    self.actionAbout_PyQt.setText(QtGui.QApplication.translate("MainWindow", "About PyQt", None, QtGui.QApplication.UnicodeUTF8))

from BookListWidget import BookListWidget
import resources_rc
