# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/gui.ui'
#
# Created: Sun Dec 25 16:17:03 2011
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
  _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
  _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
  def setupUi(self, MainWindow):
    MainWindow.setObjectName(_fromUtf8("MainWindow"))
    MainWindow.setEnabled(True)
    MainWindow.resize(713, 566)
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    MainWindow.setWindowIcon(icon)
    MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
    self.centralwidget = QtGui.QWidget(MainWindow)
    self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
    self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
    self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
    self.splitter = QtGui.QSplitter(self.centralwidget)
    self.splitter.setOrientation(QtCore.Qt.Horizontal)
    self.splitter.setObjectName(_fromUtf8("splitter"))
    self.layoutWidget = QtGui.QWidget(self.splitter)
    self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
    self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
    self.verticalLayout_3.setMargin(0)
    self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
    self.verticalLayout_2 = QtGui.QVBoxLayout()
    self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
    self.label_8 = QtGui.QLabel(self.layoutWidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
    self.label_8.setSizePolicy(sizePolicy)
    self.label_8.setAlignment(QtCore.Qt.AlignCenter)
    self.label_8.setObjectName(_fromUtf8("label_8"))
    self.verticalLayout_2.addWidget(self.label_8)
    self.pageList = BookListWidget(self.layoutWidget)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.pageList.sizePolicy().hasHeightForWidth())
    self.pageList.setSizePolicy(sizePolicy)
    self.pageList.setAcceptDrops(True)
    self.pageList.setStyleSheet(_fromUtf8("QListView\n"
"{\n"
"background-image: url(\":/icons/go-down-big.png\");\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"background-color: white;\n"
"}\n"
"\n"
"QListView:hover\n"
"{\n"
"background-image: url(\":/icons/go-down-big-hover.png\");\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"background-color: white;\n"
"}"))
    self.pageList.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
    self.pageList.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
    self.pageList.setUniformItemSizes(True)
    self.pageList.setObjectName(_fromUtf8("pageList"))
    self.verticalLayout_2.addWidget(self.pageList)
    self.verticalLayout_3.addLayout(self.verticalLayout_2)
    self.horizontalLayout = QtGui.QHBoxLayout()
    self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
    self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
    self.addPageButton = QtGui.QPushButton(self.layoutWidget)
    self.addPageButton.setObjectName(_fromUtf8("addPageButton"))
    self.horizontalLayout.addWidget(self.addPageButton)
    spacerItem = QtGui.QSpacerItem(50, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
    self.horizontalLayout.addItem(spacerItem)
    self.removePageButton = QtGui.QPushButton(self.layoutWidget)
    self.removePageButton.setEnabled(False)
    self.removePageButton.setAutoRepeat(False)
    self.removePageButton.setFlat(False)
    self.removePageButton.setObjectName(_fromUtf8("removePageButton"))
    self.horizontalLayout.addWidget(self.removePageButton)
    self.verticalLayout_3.addLayout(self.horizontalLayout)
    self.layoutWidget1 = QtGui.QWidget(self.splitter)
    self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
    self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
    self.verticalLayout.setMargin(0)
    self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
    self.tabWidget = QtGui.QTabWidget(self.layoutWidget1)
    self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
    self.tabWidget.setMovable(True)
    self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
    self.pageTab = QtGui.QWidget()
    self.pageTab.setObjectName(_fromUtf8("pageTab"))
    self.gridLayout_7 = QtGui.QGridLayout(self.pageTab)
    self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
    self.singlePageFrame = QtGui.QFrame(self.pageTab)
    self.singlePageFrame.setObjectName(_fromUtf8("singlePageFrame"))
    self.gridLayout = QtGui.QGridLayout(self.singlePageFrame)
    self.gridLayout.setMargin(0)
    self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
    self.verticalLayout1 = QtGui.QVBoxLayout()
    self.verticalLayout1.setObjectName(_fromUtf8("verticalLayout1"))
    self.label = QtGui.QLabel(self.singlePageFrame)
    self.label.setAlignment(QtCore.Qt.AlignCenter)
    self.label.setObjectName(_fromUtf8("label"))
    self.verticalLayout1.addWidget(self.label)
    self.pagePreview = ImageViewerWidget(self.singlePageFrame)
    self.pagePreview.setStyleSheet(_fromUtf8("QGraphicsView {\n"
"  background-color: rgb(240, 240, 240);\n"
"}"))
    self.pagePreview.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.SmoothPixmapTransform)
    self.pagePreview.setObjectName(_fromUtf8("pagePreview"))
    self.verticalLayout1.addWidget(self.pagePreview)
    self.horizontalLayout1 = QtGui.QHBoxLayout()
    self.horizontalLayout1.setObjectName(_fromUtf8("horizontalLayout1"))
    spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
    self.horizontalLayout1.addItem(spacerItem1)
    self.moveToTopButton = QtGui.QToolButton(self.singlePageFrame)
    self.moveToTopButton.setIconSize(QtCore.QSize(32, 32))
    self.moveToTopButton.setObjectName(_fromUtf8("moveToTopButton"))
    self.horizontalLayout1.addWidget(self.moveToTopButton)
    self.moveUpButton = QtGui.QToolButton(self.singlePageFrame)
    self.moveUpButton.setIconSize(QtCore.QSize(32, 32))
    self.moveUpButton.setObjectName(_fromUtf8("moveUpButton"))
    self.horizontalLayout1.addWidget(self.moveUpButton)
    self.moveDownButton = QtGui.QToolButton(self.singlePageFrame)
    self.moveDownButton.setIconSize(QtCore.QSize(32, 32))
    self.moveDownButton.setObjectName(_fromUtf8("moveDownButton"))
    self.horizontalLayout1.addWidget(self.moveDownButton)
    self.moveToBottomButton = QtGui.QToolButton(self.singlePageFrame)
    self.moveToBottomButton.setIconSize(QtCore.QSize(32, 32))
    self.moveToBottomButton.setObjectName(_fromUtf8("moveToBottomButton"))
    self.horizontalLayout1.addWidget(self.moveToBottomButton)
    spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
    self.horizontalLayout1.addItem(spacerItem2)
    self.verticalLayout1.addLayout(self.horizontalLayout1)
    self.gridLayout.addLayout(self.verticalLayout1, 0, 0, 1, 1)
    self.gridLayout_7.addWidget(self.singlePageFrame, 0, 0, 1, 1)
    self.formLayout_5 = QtGui.QFormLayout()
    self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
    self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
    self.pageGrayscale = QtGui.QCheckBox(self.pageTab)
    self.pageGrayscale.setObjectName(_fromUtf8("pageGrayscale"))
    self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.pageGrayscale)
    self.pageGrayscaleLabel = QtGui.QLabel(self.pageTab)
    self.pageGrayscaleLabel.setObjectName(_fromUtf8("pageGrayscaleLabel"))
    self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.pageGrayscaleLabel)
    self.gridLayout_7.addLayout(self.formLayout_5, 1, 0, 1, 1)
    self.tabWidget.addTab(self.pageTab, _fromUtf8(""))
    self.bookTab = QtGui.QWidget()
    self.bookTab.setObjectName(_fromUtf8("bookTab"))
    self.formLayout_3 = QtGui.QFormLayout(self.bookTab)
    self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
    self.outputFormatLabel = QtGui.QLabel(self.bookTab)
    self.outputFormatLabel.setObjectName(_fromUtf8("outputFormatLabel"))
    self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.outputFormatLabel)
    self.outputFormat = QtGui.QComboBox(self.bookTab)
    self.outputFormat.setObjectName(_fromUtf8("outputFormat"))
    self.outputFormat.addItem(_fromUtf8(""))
    self.outputFormat.addItem(_fromUtf8(""))
    self.outputFormat.addItem(_fromUtf8(""))
    self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.outputFormat)
    self.outputFileLabel = QtGui.QLabel(self.bookTab)
    self.outputFileLabel.setObjectName(_fromUtf8("outputFileLabel"))
    self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.outputFileLabel)
    self.horizontalLayout_2 = QtGui.QHBoxLayout()
    self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
    self.outputFile = QtGui.QLineEdit(self.bookTab)
    self.outputFile.setObjectName(_fromUtf8("outputFile"))
    self.horizontalLayout_2.addWidget(self.outputFile)
    self.outputFileBrowseButton = QtGui.QPushButton(self.bookTab)
    self.outputFileBrowseButton.setObjectName(_fromUtf8("outputFileBrowseButton"))
    self.horizontalLayout_2.addWidget(self.outputFileBrowseButton)
    self.formLayout_3.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
    self.label_4 = QtGui.QLabel(self.bookTab)
    self.label_4.setObjectName(_fromUtf8("label_4"))
    self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
    self.pageScale = QtGui.QSpinBox(self.bookTab)
    self.pageScale.setMinimum(1)
    self.pageScale.setMaximum(200)
    self.pageScale.setProperty("value", 100)
    self.pageScale.setObjectName(_fromUtf8("pageScale"))
    self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.pageScale)
    self.pageGrayscaleLabel_2 = QtGui.QLabel(self.bookTab)
    self.pageGrayscaleLabel_2.setObjectName(_fromUtf8("pageGrayscaleLabel_2"))
    self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.pageGrayscaleLabel_2)
    self.pageGrayscale2 = QtGui.QCheckBox(self.bookTab)
    self.pageGrayscale2.setObjectName(_fromUtf8("pageGrayscale2"))
    self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.pageGrayscale2)
    self.tabWidget.addTab(self.bookTab, _fromUtf8(""))
    self.ocrTab = QtGui.QWidget()
    self.ocrTab.setObjectName(_fromUtf8("ocrTab"))
    self.gridLayout_3 = QtGui.QGridLayout(self.ocrTab)
    self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
    self.enableOCR = QtGui.QCheckBox(self.ocrTab)
    self.enableOCR.setObjectName(_fromUtf8("enableOCR"))
    self.gridLayout_3.addWidget(self.enableOCR, 0, 0, 1, 1)
    self.frame = QtGui.QFrame(self.ocrTab)
    self.frame.setEnabled(False)
    self.frame.setObjectName(_fromUtf8("frame"))
    self.formLayout_2 = QtGui.QFormLayout(self.frame)
    self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
    self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
    self.ocrEngineLabel = QtGui.QLabel(self.frame)
    self.ocrEngineLabel.setObjectName(_fromUtf8("ocrEngineLabel"))
    self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.ocrEngineLabel)
    self.ocrEngine = QtGui.QComboBox(self.frame)
    self.ocrEngine.setObjectName(_fromUtf8("ocrEngine"))
    self.ocrEngine.addItem(_fromUtf8(""))
    self.ocrEngine.addItem(_fromUtf8(""))
    self.ocrEngine.addItem(_fromUtf8(""))
    self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.ocrEngine)
    self.ocrLanguageLabel = QtGui.QLabel(self.frame)
    self.ocrLanguageLabel.setObjectName(_fromUtf8("ocrLanguageLabel"))
    self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.ocrLanguageLabel)
    self.ocrLanguage = QtGui.QComboBox(self.frame)
    self.ocrLanguage.setObjectName(_fromUtf8("ocrLanguage"))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.ocrLanguage.addItem(_fromUtf8(""))
    self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.ocrLanguage)
    self.ocrOptionsLabel = QtGui.QLabel(self.frame)
    self.ocrOptionsLabel.setObjectName(_fromUtf8("ocrOptionsLabel"))
    self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.ocrOptionsLabel)
    self.ocrOptions = QtGui.QLineEdit(self.frame)
    self.ocrOptions.setLayoutDirection(QtCore.Qt.LeftToRight)
    self.ocrOptions.setObjectName(_fromUtf8("ocrOptions"))
    self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.ocrOptions)
    self.stackedWidget_2 = QtGui.QStackedWidget(self.frame)
    self.stackedWidget_2.setObjectName(_fromUtf8("stackedWidget_2"))
    self.page_6 = QtGui.QWidget()
    self.page_6.setObjectName(_fromUtf8("page_6"))
    self.stackedWidget_2.addWidget(self.page_6)
    self.page_3 = QtGui.QWidget()
    self.page_3.setObjectName(_fromUtf8("page_3"))
    self.gridLayout_6 = QtGui.QGridLayout(self.page_3)
    self.gridLayout_6.setContentsMargins(0, 6, 0, 0)
    self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
    self.label_3 = QtGui.QLabel(self.page_3)
    self.label_3.setObjectName(_fromUtf8("label_3"))
    self.gridLayout_6.addWidget(self.label_3, 0, 0, 1, 1)
    self.stackedWidget_2.addWidget(self.page_3)
    self.page_4 = QtGui.QWidget()
    self.page_4.setObjectName(_fromUtf8("page_4"))
    self.stackedWidget_2.addWidget(self.page_4)
    self.formLayout_2.setWidget(3, QtGui.QFormLayout.SpanningRole, self.stackedWidget_2)
    self.gridLayout_3.addWidget(self.frame, 1, 0, 1, 1)
    self.tabWidget.addTab(self.ocrTab, _fromUtf8(""))
    self.encodingTab = QtGui.QWidget()
    self.encodingTab.setObjectName(_fromUtf8("encodingTab"))
    self.gridLayout_4 = QtGui.QGridLayout(self.encodingTab)
    self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
    self.stackedWidget = QtGui.QStackedWidget(self.encodingTab)
    self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
    self.page = QtGui.QWidget()
    self.page.setObjectName(_fromUtf8("page"))
    self.formLayout = QtGui.QFormLayout(self.page)
    self.formLayout.setObjectName(_fromUtf8("formLayout"))
    self.bitonalEncoderLabel = QtGui.QLabel(self.page)
    self.bitonalEncoderLabel.setObjectName(_fromUtf8("bitonalEncoderLabel"))
    self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.bitonalEncoderLabel)
    self.djvuBitonalEncoder = QtGui.QComboBox(self.page)
    self.djvuBitonalEncoder.setObjectName(_fromUtf8("djvuBitonalEncoder"))
    self.djvuBitonalEncoder.addItem(_fromUtf8(""))
    self.djvuBitonalEncoder.addItem(_fromUtf8(""))
    self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.djvuBitonalEncoder)
    self.colorEncoderLabel = QtGui.QLabel(self.page)
    self.colorEncoderLabel.setObjectName(_fromUtf8("colorEncoderLabel"))
    self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.colorEncoderLabel)
    self.djvuColorEncoder = QtGui.QComboBox(self.page)
    self.djvuColorEncoder.setObjectName(_fromUtf8("djvuColorEncoder"))
    self.djvuColorEncoder.addItem(_fromUtf8(""))
    self.djvuColorEncoder.addItem(_fromUtf8(""))
    self.djvuColorEncoder.addItem(_fromUtf8(""))
    self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.djvuColorEncoder)
    self.c44OptionsLabel = QtGui.QLabel(self.page)
    self.c44OptionsLabel.setObjectName(_fromUtf8("c44OptionsLabel"))
    self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.c44OptionsLabel)
    self.c44Options = QtGui.QLineEdit(self.page)
    self.c44Options.setObjectName(_fromUtf8("c44Options"))
    self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.c44Options)
    self.cjb2OptionsLabel = QtGui.QLabel(self.page)
    self.cjb2OptionsLabel.setObjectName(_fromUtf8("cjb2OptionsLabel"))
    self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.cjb2OptionsLabel)
    self.cjb2Options = QtGui.QLineEdit(self.page)
    self.cjb2Options.setObjectName(_fromUtf8("cjb2Options"))
    self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.cjb2Options)
    self.cpaldjvuOptionsLabel = QtGui.QLabel(self.page)
    self.cpaldjvuOptionsLabel.setObjectName(_fromUtf8("cpaldjvuOptionsLabel"))
    self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.cpaldjvuOptionsLabel)
    self.cpaldjvuOptions = QtGui.QLineEdit(self.page)
    self.cpaldjvuOptions.setObjectName(_fromUtf8("cpaldjvuOptions"))
    self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.cpaldjvuOptions)
    self.csepdjvuOptionsLabel = QtGui.QLabel(self.page)
    self.csepdjvuOptionsLabel.setObjectName(_fromUtf8("csepdjvuOptionsLabel"))
    self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.csepdjvuOptionsLabel)
    self.csepdjvuOptions = QtGui.QLineEdit(self.page)
    self.csepdjvuOptions.setObjectName(_fromUtf8("csepdjvuOptions"))
    self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.csepdjvuOptions)
    self.minidjvuOptionsLabel = QtGui.QLabel(self.page)
    self.minidjvuOptionsLabel.setObjectName(_fromUtf8("minidjvuOptionsLabel"))
    self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.minidjvuOptionsLabel)
    self.minidjvuOptions = QtGui.QLineEdit(self.page)
    self.minidjvuOptions.setCursorPosition(27)
    self.minidjvuOptions.setObjectName(_fromUtf8("minidjvuOptions"))
    self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.minidjvuOptions)
    self.stackedWidget.addWidget(self.page)
    self.page_2 = QtGui.QWidget()
    self.page_2.setObjectName(_fromUtf8("page_2"))
    self.formLayout_4 = QtGui.QFormLayout(self.page_2)
    self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
    self.label_2 = QtGui.QLabel(self.page_2)
    self.label_2.setObjectName(_fromUtf8("label_2"))
    self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
    self.pdfBitonalEncoder = QtGui.QComboBox(self.page_2)
    self.pdfBitonalEncoder.setObjectName(_fromUtf8("pdfBitonalEncoder"))
    self.pdfBitonalEncoder.addItem(_fromUtf8(""))
    self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.pdfBitonalEncoder)
    self.stackedWidget.addWidget(self.page_2)
    self.gridLayout_4.addWidget(self.stackedWidget, 0, 0, 1, 1)
    self.tabWidget.addTab(self.encodingTab, _fromUtf8(""))
    self.debugTab = QtGui.QWidget()
    self.debugTab.setEnabled(True)
    self.debugTab.setObjectName(_fromUtf8("debugTab"))
    self.gridLayout_5 = QtGui.QGridLayout(self.debugTab)
    self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
    self.debugLog = DebugLog(self.debugTab)
    self.debugLog.setIndentation(0)
    self.debugLog.setUniformRowHeights(True)
    self.debugLog.setAnimated(True)
    self.debugLog.setWordWrap(True)
    self.debugLog.setObjectName(_fromUtf8("debugLog"))
    self.debugLog.header().setCascadingSectionResizes(True)
    self.debugLog.header().setMinimumSectionSize(20)
    self.debugLog.header().setSortIndicatorShown(True)
    self.gridLayout_5.addWidget(self.debugLog, 0, 0, 1, 3)
    self.clearLogButton = QtGui.QPushButton(self.debugTab)
    self.clearLogButton.setObjectName(_fromUtf8("clearLogButton"))
    self.gridLayout_5.addWidget(self.clearLogButton, 1, 0, 1, 1)
    spacerItem3 = QtGui.QSpacerItem(220, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
    self.gridLayout_5.addItem(spacerItem3, 1, 1, 1, 1)
    self.saveLogButton = QtGui.QPushButton(self.debugTab)
    self.saveLogButton.setObjectName(_fromUtf8("saveLogButton"))
    self.gridLayout_5.addWidget(self.saveLogButton, 1, 2, 1, 1)
    self.tabWidget.addTab(self.debugTab, _fromUtf8(""))
    self.verticalLayout.addWidget(self.tabWidget)
    self.horizontalLayout_7 = QtGui.QHBoxLayout()
    self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
    self.progressBar = QtGui.QProgressBar(self.layoutWidget1)
    self.progressBar.setObjectName(_fromUtf8("progressBar"))
    self.horizontalLayout_7.addWidget(self.progressBar)
    self.startButton = QtGui.QPushButton(self.layoutWidget1)
    self.startButton.setEnabled(False)
    self.startButton.setObjectName(_fromUtf8("startButton"))
    self.horizontalLayout_7.addWidget(self.startButton)
    self.verticalLayout.addLayout(self.horizontalLayout_7)
    self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
    MainWindow.setCentralWidget(self.centralwidget)
    self.menuBar = QtGui.QMenuBar(MainWindow)
    self.menuBar.setGeometry(QtCore.QRect(0, 0, 713, 25))
    self.menuBar.setObjectName(_fromUtf8("menuBar"))
    self.menuFile = QtGui.QMenu(self.menuBar)
    self.menuFile.setObjectName(_fromUtf8("menuFile"))
    self.menuEdit = QtGui.QMenu(self.menuBar)
    self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
    self.menuAbout = QtGui.QMenu(self.menuBar)
    self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
    self.menuView = QtGui.QMenu(self.menuBar)
    self.menuView.setObjectName(_fromUtf8("menuView"))
    self.menuPage_Style = QtGui.QMenu(self.menuView)
    self.menuPage_Style.setObjectName(_fromUtf8("menuPage_Style"))
    self.menuPage = QtGui.QMenu(self.menuBar)
    self.menuPage.setObjectName(_fromUtf8("menuPage"))
    MainWindow.setMenuBar(self.menuBar)
    self.toolBar = QtGui.QToolBar(MainWindow)
    self.toolBar.setMovable(False)
    self.toolBar.setObjectName(_fromUtf8("toolBar"))
    MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
    self.newMenuItem = QtGui.QAction(MainWindow)
    self.newMenuItem.setObjectName(_fromUtf8("newMenuItem"))
    self.openMenuItem = QtGui.QAction(MainWindow)
    self.openMenuItem.setObjectName(_fromUtf8("openMenuItem"))
    self.saveMenuItem = QtGui.QAction(MainWindow)
    self.saveMenuItem.setObjectName(_fromUtf8("saveMenuItem"))
    self.saveAsMenuItem = QtGui.QAction(MainWindow)
    self.saveAsMenuItem.setObjectName(_fromUtf8("saveAsMenuItem"))
    self.quitMenuItem = QtGui.QAction(MainWindow)
    self.quitMenuItem.setMenuRole(QtGui.QAction.QuitRole)
    self.quitMenuItem.setObjectName(_fromUtf8("quitMenuItem"))
    self.helpMenuItem = QtGui.QAction(MainWindow)
    self.helpMenuItem.setObjectName(_fromUtf8("helpMenuItem"))
    self.aboutMenuItem = QtGui.QAction(MainWindow)
    self.aboutMenuItem.setObjectName(_fromUtf8("aboutMenuItem"))
    self.filePreviewsMenuItem = QtGui.QAction(MainWindow)
    self.filePreviewsMenuItem.setCheckable(True)
    self.filePreviewsMenuItem.setChecked(True)
    self.filePreviewsMenuItem.setObjectName(_fromUtf8("filePreviewsMenuItem"))
    self.advancedOptionsMenuItem = QtGui.QAction(MainWindow)
    self.advancedOptionsMenuItem.setCheckable(True)
    self.advancedOptionsMenuItem.setChecked(True)
    self.advancedOptionsMenuItem.setObjectName(_fromUtf8("advancedOptionsMenuItem"))
    self.actionAbout_Qt4 = QtGui.QAction(MainWindow)
    self.actionAbout_Qt4.setMenuRole(QtGui.QAction.AboutQtRole)
    self.actionAbout_Qt4.setObjectName(_fromUtf8("actionAbout_Qt4"))
    self.actionAbout_PyQt = QtGui.QAction(MainWindow)
    self.actionAbout_PyQt.setObjectName(_fromUtf8("actionAbout_PyQt"))
    self.actionList = QtGui.QAction(MainWindow)
    self.actionList.setCheckable(True)
    self.actionList.setChecked(True)
    self.actionList.setObjectName(_fromUtf8("actionList"))
    self.actionIcon = QtGui.QAction(MainWindow)
    self.actionIcon.setCheckable(True)
    self.actionIcon.setObjectName(_fromUtf8("actionIcon"))
    self.actionAdvanced_Mode = QtGui.QAction(MainWindow)
    self.actionAdvanced_Mode.setCheckable(True)
    self.actionAdvanced_Mode.setChecked(True)
    self.actionAdvanced_Mode.setObjectName(_fromUtf8("actionAdvanced_Mode"))
    self.addPageMenuItem = QtGui.QAction(MainWindow)
    self.addPageMenuItem.setObjectName(_fromUtf8("addPageMenuItem"))
    self.removePageMenuItem = QtGui.QAction(MainWindow)
    self.removePageMenuItem.setObjectName(_fromUtf8("removePageMenuItem"))
    self.startBindingMenuItem = QtGui.QAction(MainWindow)
    self.startBindingMenuItem.setObjectName(_fromUtf8("startBindingMenuItem"))
    self.menuFile.addAction(self.newMenuItem)
    self.menuFile.addAction(self.openMenuItem)
    self.menuFile.addSeparator()
    self.menuFile.addAction(self.saveMenuItem)
    self.menuFile.addAction(self.saveAsMenuItem)
    self.menuFile.addSeparator()
    self.menuFile.addAction(self.quitMenuItem)
    self.menuAbout.addAction(self.helpMenuItem)
    self.menuAbout.addSeparator()
    self.menuAbout.addAction(self.aboutMenuItem)
    self.menuAbout.addAction(self.actionAbout_Qt4)
    self.menuAbout.addAction(self.actionAbout_PyQt)
    self.menuPage_Style.addAction(self.actionList)
    self.menuPage_Style.addAction(self.actionIcon)
    self.menuView.addAction(self.menuPage_Style.menuAction())
    self.menuView.addAction(self.filePreviewsMenuItem)
    self.menuPage.addAction(self.addPageMenuItem)
    self.menuPage.addAction(self.removePageMenuItem)
    self.menuBar.addAction(self.menuFile.menuAction())
    self.menuBar.addAction(self.menuEdit.menuAction())
    self.menuBar.addAction(self.menuPage.menuAction())
    self.menuBar.addAction(self.menuView.menuAction())
    self.menuBar.addAction(self.menuAbout.menuAction())
    self.toolBar.addAction(self.newMenuItem)
    self.toolBar.addAction(self.openMenuItem)
    self.toolBar.addAction(self.saveMenuItem)
    self.toolBar.addSeparator()
    self.toolBar.addAction(self.addPageMenuItem)
    self.toolBar.addAction(self.removePageMenuItem)
    self.toolBar.addSeparator()
    self.toolBar.addAction(self.startBindingMenuItem)

    self.retranslateUi(MainWindow)
    self.tabWidget.setCurrentIndex(0)
    self.outputFormat.setCurrentIndex(0)
    self.ocrLanguage.setCurrentIndex(5)
    self.stackedWidget_2.setCurrentIndex(0)
    self.stackedWidget.setCurrentIndex(0)
    QtCore.QObject.connect(self.addPageButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.addFiles)
    QtCore.QObject.connect(self.removePageButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.removeFiles)
    QtCore.QObject.connect(self.pageList, QtCore.SIGNAL(_fromUtf8("dropped(QStringList)")), MainWindow.filesDropped)
    QtCore.QObject.connect(self.startButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.toggleBinding)
    QtCore.QObject.connect(self.startBindingMenuItem, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.toggleBinding)
    QtCore.QObject.connect(self.newMenuItem, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.showProjectDialog)
    QtCore.QObject.connect(self.filePreviewsMenuItem, QtCore.SIGNAL(_fromUtf8("triggered(bool)")), MainWindow.togglePreviews)
    QtCore.QObject.connect(self.pageList, QtCore.SIGNAL(_fromUtf8("itemSelectionChanged()")), MainWindow.itemSelectionChanged)
    QtCore.QObject.connect(self.removePageMenuItem, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.removeFiles)
    QtCore.QObject.connect(self.addPageMenuItem, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.addFiles)
    QtCore.QObject.connect(self.moveDownButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.moveItemDown)
    QtCore.QObject.connect(self.moveToTopButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.moveItemToTop)
    QtCore.QObject.connect(self.moveUpButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.moveItemUp)
    QtCore.QObject.connect(self.enableOCR, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame.setEnabled)
    QtCore.QObject.connect(self.moveToBottomButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.moveItemToBottom)
    QtCore.QObject.connect(self.ocrLanguage, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), MainWindow.changeOCRLanguage)
    QtCore.QObject.connect(self.outputFileBrowseButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.showSaveDialog)
    QtCore.QObject.connect(self.outputFormat, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.outputFormatChanged)
    QtCore.QObject.connect(self.clearLogButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.clearDebugLog)
    QtCore.QObject.connect(self.saveLogButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.saveDebugLog)
    QtCore.QObject.connect(self.ocrEngine, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.stackedWidget_2.setCurrentIndex)
    QtCore.QObject.connect(self.pageGrayscale, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.pageGrayscaleChanged)
    QtCore.QMetaObject.connectSlotsByName(MainWindow)

  def retranslateUi(self, MainWindow):
    MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Bindery", None, QtGui.QApplication.UnicodeUTF8))
    self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Add and arrange the book\'s pages below", None, QtGui.QApplication.UnicodeUTF8))
    self.addPageButton.setText(QtGui.QApplication.translate("MainWindow", "Add page", None, QtGui.QApplication.UnicodeUTF8))
    self.removePageButton.setText(QtGui.QApplication.translate("MainWindow", "Remove page", None, QtGui.QApplication.UnicodeUTF8))
    self.label.setText(QtGui.QApplication.translate("MainWindow", "Page Preview", None, QtGui.QApplication.UnicodeUTF8))
    self.moveToTopButton.setText(QtGui.QApplication.translate("MainWindow", "Very Top", None, QtGui.QApplication.UnicodeUTF8))
    self.moveUpButton.setText(QtGui.QApplication.translate("MainWindow", "Move Up", None, QtGui.QApplication.UnicodeUTF8))
    self.moveDownButton.setText(QtGui.QApplication.translate("MainWindow", "Move Down", None, QtGui.QApplication.UnicodeUTF8))
    self.moveToBottomButton.setText(QtGui.QApplication.translate("MainWindow", "Very Bottom", None, QtGui.QApplication.UnicodeUTF8))
    self.pageGrayscaleLabel.setText(QtGui.QApplication.translate("MainWindow", "Convert to grayscale", None, QtGui.QApplication.UnicodeUTF8))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.pageTab), QtGui.QApplication.translate("MainWindow", "Page", None, QtGui.QApplication.UnicodeUTF8))
    self.outputFormatLabel.setText(QtGui.QApplication.translate("MainWindow", "Output Format", None, QtGui.QApplication.UnicodeUTF8))
    self.outputFormat.setItemText(0, QtGui.QApplication.translate("MainWindow", "DjVu", None, QtGui.QApplication.UnicodeUTF8))
    self.outputFormat.setItemText(1, QtGui.QApplication.translate("MainWindow", "PDF", None, QtGui.QApplication.UnicodeUTF8))
    self.outputFormat.setItemText(2, QtGui.QApplication.translate("MainWindow", "PostScript", None, QtGui.QApplication.UnicodeUTF8))
    self.outputFileLabel.setText(QtGui.QApplication.translate("MainWindow", "Output File", None, QtGui.QApplication.UnicodeUTF8))
    self.outputFile.setText(QtGui.QApplication.translate("MainWindow", "/media/Data Drive/Output/OW/", None, QtGui.QApplication.UnicodeUTF8))
    self.outputFileBrowseButton.setText(QtGui.QApplication.translate("MainWindow", "Browse", None, QtGui.QApplication.UnicodeUTF8))
    self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Scale Pages", None, QtGui.QApplication.UnicodeUTF8))
    self.pageScale.setSuffix(QtGui.QApplication.translate("MainWindow", "%", None, QtGui.QApplication.UnicodeUTF8))
    self.pageGrayscaleLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Convert to grayscale", None, QtGui.QApplication.UnicodeUTF8))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.bookTab), QtGui.QApplication.translate("MainWindow", "Book", None, QtGui.QApplication.UnicodeUTF8))
    self.enableOCR.setText(QtGui.QApplication.translate("MainWindow", "Enable OCR", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrEngineLabel.setText(QtGui.QApplication.translate("MainWindow", "OCR Engine", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrEngine.setItemText(0, QtGui.QApplication.translate("MainWindow", "Tesseract", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrEngine.setItemText(1, QtGui.QApplication.translate("MainWindow", "OCRopus", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrEngine.setItemText(2, QtGui.QApplication.translate("MainWindow", "Cuniform", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguageLabel.setText(QtGui.QApplication.translate("MainWindow", "Language", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(0, QtGui.QApplication.translate("MainWindow", "Bulgarian", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(1, QtGui.QApplication.translate("MainWindow", "Catalan", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(2, QtGui.QApplication.translate("MainWindow", "Czech", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(3, QtGui.QApplication.translate("MainWindow", "Danish", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(4, QtGui.QApplication.translate("MainWindow", "Dutch", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(5, QtGui.QApplication.translate("MainWindow", "English", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(6, QtGui.QApplication.translate("MainWindow", "Finnish", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(7, QtGui.QApplication.translate("MainWindow", "French", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(8, QtGui.QApplication.translate("MainWindow", "German", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(9, QtGui.QApplication.translate("MainWindow", "Greek", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(10, QtGui.QApplication.translate("MainWindow", "Hungarian", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(11, QtGui.QApplication.translate("MainWindow", "Indonesian", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(12, QtGui.QApplication.translate("MainWindow", "Italian", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(13, QtGui.QApplication.translate("MainWindow", "Latvian", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(14, QtGui.QApplication.translate("MainWindow", "Lithuanian", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(15, QtGui.QApplication.translate("MainWindow", "Norwegian", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(16, QtGui.QApplication.translate("MainWindow", "Polish", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(17, QtGui.QApplication.translate("MainWindow", "Portugese", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(18, QtGui.QApplication.translate("MainWindow", "Romanian", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(19, QtGui.QApplication.translate("MainWindow", "Russian", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(20, QtGui.QApplication.translate("MainWindow", "Serbian", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(21, QtGui.QApplication.translate("MainWindow", "Slovak", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(22, QtGui.QApplication.translate("MainWindow", "Slovenian", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(23, QtGui.QApplication.translate("MainWindow", "Spanish", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(24, QtGui.QApplication.translate("MainWindow", "Swedish", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(25, QtGui.QApplication.translate("MainWindow", "Tagalog", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(26, QtGui.QApplication.translate("MainWindow", "Turkish", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(27, QtGui.QApplication.translate("MainWindow", "Ukranian", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrLanguage.setItemText(28, QtGui.QApplication.translate("MainWindow", "Vietnamese", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrOptionsLabel.setText(QtGui.QApplication.translate("MainWindow", "Engine Options", None, QtGui.QApplication.UnicodeUTF8))
    self.ocrOptions.setText(QtGui.QApplication.translate("MainWindow", "-l eng", None, QtGui.QApplication.UnicodeUTF8))
    self.label_3.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">OCRopus produces text-only documents!</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.ocrTab), QtGui.QApplication.translate("MainWindow", "OCR", None, QtGui.QApplication.UnicodeUTF8))
    self.bitonalEncoderLabel.setText(QtGui.QApplication.translate("MainWindow", "Bitonal Encoder", None, QtGui.QApplication.UnicodeUTF8))
    self.djvuBitonalEncoder.setItemText(0, QtGui.QApplication.translate("MainWindow", "cjb2", None, QtGui.QApplication.UnicodeUTF8))
    self.djvuBitonalEncoder.setItemText(1, QtGui.QApplication.translate("MainWindow", "minidjvu", None, QtGui.QApplication.UnicodeUTF8))
    self.colorEncoderLabel.setText(QtGui.QApplication.translate("MainWindow", "Color Encoder", None, QtGui.QApplication.UnicodeUTF8))
    self.djvuColorEncoder.setItemText(0, QtGui.QApplication.translate("MainWindow", "csepdjvu", None, QtGui.QApplication.UnicodeUTF8))
    self.djvuColorEncoder.setItemText(1, QtGui.QApplication.translate("MainWindow", "c44", None, QtGui.QApplication.UnicodeUTF8))
    self.djvuColorEncoder.setItemText(2, QtGui.QApplication.translate("MainWindow", "cpaldjvu", None, QtGui.QApplication.UnicodeUTF8))
    self.c44OptionsLabel.setText(QtGui.QApplication.translate("MainWindow", "c44 Options", None, QtGui.QApplication.UnicodeUTF8))
    self.cjb2OptionsLabel.setText(QtGui.QApplication.translate("MainWindow", "cjb2 Options", None, QtGui.QApplication.UnicodeUTF8))
    self.cjb2Options.setText(QtGui.QApplication.translate("MainWindow", "-lossy", None, QtGui.QApplication.UnicodeUTF8))
    self.cpaldjvuOptionsLabel.setText(QtGui.QApplication.translate("MainWindow", "cpaldjvu Options", None, QtGui.QApplication.UnicodeUTF8))
    self.csepdjvuOptionsLabel.setText(QtGui.QApplication.translate("MainWindow", "csepdjvu Options", None, QtGui.QApplication.UnicodeUTF8))
    self.minidjvuOptionsLabel.setText(QtGui.QApplication.translate("MainWindow", "minidjvu Options", None, QtGui.QApplication.UnicodeUTF8))
    self.minidjvuOptions.setText(QtGui.QApplication.translate("MainWindow", "--match -pages-per-dict 100", None, QtGui.QApplication.UnicodeUTF8))
    self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Bitonal Encoder", None, QtGui.QApplication.UnicodeUTF8))
    self.pdfBitonalEncoder.setItemText(0, QtGui.QApplication.translate("MainWindow", "jbig2", None, QtGui.QApplication.UnicodeUTF8))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.encodingTab), QtGui.QApplication.translate("MainWindow", "Encoding Options", None, QtGui.QApplication.UnicodeUTF8))
    self.debugLog.setSortingEnabled(True)
    self.debugLog.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Time", None, QtGui.QApplication.UnicodeUTF8))
    self.debugLog.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Sender", None, QtGui.QApplication.UnicodeUTF8))
    self.debugLog.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Event", None, QtGui.QApplication.UnicodeUTF8))
    self.debugLog.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Level", None, QtGui.QApplication.UnicodeUTF8))
    self.clearLogButton.setText(QtGui.QApplication.translate("MainWindow", "Clear log", None, QtGui.QApplication.UnicodeUTF8))
    self.saveLogButton.setText(QtGui.QApplication.translate("MainWindow", "Save log", None, QtGui.QApplication.UnicodeUTF8))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.debugTab), QtGui.QApplication.translate("MainWindow", "Debug Log", None, QtGui.QApplication.UnicodeUTF8))
    self.progressBar.setFormat(QtGui.QApplication.translate("MainWindow", "%p%", None, QtGui.QApplication.UnicodeUTF8))
    self.startButton.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
    self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
    self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
    self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
    self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "&View", None, QtGui.QApplication.UnicodeUTF8))
    self.menuPage_Style.setTitle(QtGui.QApplication.translate("MainWindow", "Page Style", None, QtGui.QApplication.UnicodeUTF8))
    self.menuPage.setTitle(QtGui.QApplication.translate("MainWindow", "Page", None, QtGui.QApplication.UnicodeUTF8))
    self.newMenuItem.setText(QtGui.QApplication.translate("MainWindow", "&New", None, QtGui.QApplication.UnicodeUTF8))
    self.newMenuItem.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
    self.openMenuItem.setText(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
    self.openMenuItem.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
    self.saveMenuItem.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
    self.saveMenuItem.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
    self.saveAsMenuItem.setText(QtGui.QApplication.translate("MainWindow", "Save &As...", None, QtGui.QApplication.UnicodeUTF8))
    self.saveAsMenuItem.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Alt+S", None, QtGui.QApplication.UnicodeUTF8))
    self.quitMenuItem.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
    self.quitMenuItem.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
    self.helpMenuItem.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
    self.helpMenuItem.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
    self.aboutMenuItem.setText(QtGui.QApplication.translate("MainWindow", "About Bindery", None, QtGui.QApplication.UnicodeUTF8))
    self.filePreviewsMenuItem.setText(QtGui.QApplication.translate("MainWindow", "File Previews", None, QtGui.QApplication.UnicodeUTF8))
    self.advancedOptionsMenuItem.setText(QtGui.QApplication.translate("MainWindow", "Advanced Options", None, QtGui.QApplication.UnicodeUTF8))
    self.actionAbout_Qt4.setText(QtGui.QApplication.translate("MainWindow", "About Qt", None, QtGui.QApplication.UnicodeUTF8))
    self.actionAbout_PyQt.setText(QtGui.QApplication.translate("MainWindow", "About PyQt", None, QtGui.QApplication.UnicodeUTF8))
    self.actionList.setText(QtGui.QApplication.translate("MainWindow", "List", None, QtGui.QApplication.UnicodeUTF8))
    self.actionIcon.setText(QtGui.QApplication.translate("MainWindow", "Icon", None, QtGui.QApplication.UnicodeUTF8))
    self.actionAdvanced_Mode.setText(QtGui.QApplication.translate("MainWindow", "Advanced Mode", None, QtGui.QApplication.UnicodeUTF8))
    self.addPageMenuItem.setText(QtGui.QApplication.translate("MainWindow", "Add Page", None, QtGui.QApplication.UnicodeUTF8))
    self.removePageMenuItem.setText(QtGui.QApplication.translate("MainWindow", "Remove Page", None, QtGui.QApplication.UnicodeUTF8))
    self.startBindingMenuItem.setText(QtGui.QApplication.translate("MainWindow", "Start Binding", None, QtGui.QApplication.UnicodeUTF8))

from ImageViewerWidget import ImageViewerWidget
from BookListWidget import BookListWidget
from DebugLog import DebugLog
import resources_rc
